#ifndef TESSERACT_QT_RENDERING_OGRE2_OGRE2_GRAPHICS_API_H
#define TESSERACT_QT_RENDERING_OGRE2_OGRE2_GRAPHICS_API_H

namespace tesseract_gui
{
enum class GraphicsAPI
{
  OPENGL,
  DIRECT3D11,
  VULKAN,
  METAL
};

}
#endif  // TESSERACT_QT_RENDERING_OGRE2_OGRE2_GRAPHICS_API_H
